// Tailwind CSS Configuration
tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-background": "#251819",
                "on-secondary-container": "#616363",
                "error": "#ba1a1a",
                "tertiary-fixed": "#ffdadb",
                "on-secondary-fixed-variant": "#454747",
                "on-secondary": "#ffffff",
                "on-secondary-fixed": "#1a1c1c",
                "error-container": "#ffdad6",
                "inverse-on-surface": "#ffedec",
                "on-error-container": "#93000a",
                "surface-container-low": "#fff0f0",
                "outline-variant": "#e0bfbf",
                "on-surface-variant": "#594141",
                "on-tertiary-container": "#fffbff",
                "on-tertiary-fixed-variant": "#7f2734",
                "surface-container-high": "#fce2e2",
                "tertiary-container": "#ba545f",
                "surface-tint": "#b1293e",
                "on-tertiary-fixed": "#40000e",
                "surface-container-lowest": "#ffffff",
                "surface": "#fff8f7",
                "on-surface": "#251819",
                "tertiary-fixed-dim": "#ffb2b7",
                "on-error": "#ffffff",
                "secondary-fixed-dim": "#c6c6c7",
                "on-primary-container": "#fffbff",
                "tertiary": "#9b3c48",
                "surface-variant": "#f6dddd",
                "on-primary-fixed": "#40000c",
                "primary": "#ae263c",
                "on-primary-fixed-variant": "#8f0a29",
                "secondary": "#5d5f5f",
                "surface-bright": "#fff8f7",
                "secondary-fixed": "#e2e2e2",
                "surface-container-highest": "#f6dddd",
                "inverse-primary": "#ffb3b6",
                "primary-fixed": "#ffdada",
                "surface-dim": "#edd4d4",
                "surface-container": "#ffe9e9",
                "primary-fixed-dim": "#ffb3b6",
                "inverse-surface": "#3c2d2d",
                "background": "#fff8f7",
                "on-primary": "#ffffff",
                "primary-container": "#d04053",
                "outline": "#8c7071",
                "secondary-container": "#dfe0e0",
                "on-tertiary": "#ffffff"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "12px",
                "2xl": "24px",
                "full": "9999px"
            },
            "spacing": {
                "base": "8px",
                "container-max": "1440px",
                "xl": "80px",
                "xs": "4px",
                "lg": "48px",
                "gutter": "24px",
                "md": "24px",
                "sm": "12px"
            },
            "fontFamily": {
                "label-sm": ["Inter"],
                "body-md": ["Inter"],
                "display-lg-mobile": ["Poppins"],
                "headline-lg": ["Poppins"],
                "headline-md": ["Poppins"],
                "body-lg": ["Inter"],
                "display-lg": ["Poppins"]
            },
            "fontSize": {
                "label-sm": ["13px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
                "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "display-lg-mobile": ["40px", { "lineHeight": "1.2", "fontWeight": "700" }],
                "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "700" }],
                "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
                "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }]
            }
        },
    },
};
